baseURL = 'https://tomitribe.github.io/pixie/'
languageCode = 'en-us'
title = 'Pixie Documentation'

[params]
  description = 'Documentation for Pixie by Tomitribe'
  brand = 'Pixie'
  tagline = 'by Tomitribe'
  image = 'images/social-card.png'

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Docs'
    url = '/getting-started/'
    weight = 1
  [[menu.main]]
    name = 'Annotations'
    url = '/annotations/'
    weight = 2
  [[menu.main]]
    name = 'References'
    url = '/references/'
    weight = 3
  [[menu.main]]
    name = 'Producers'
    url = '/producers/'
    weight = 4
  [[menu.main]]
    name = 'Events'
    url = '/events/'
    weight = 5
  [[menu.main]]
    name = 'Testing'
    url = '/testing/'
    weight = 6
  [[menu.main]]
    name = 'Configuration'
    url = '/configuration/'
    weight = 7
  [[menu.main]]
    name = 'Changelog'
    url = '/changelog/'
    weight = 8
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/tomitribe/pixie'
    weight = 9
    [menu.main.params]
      external = true
